services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "/api/v1/"
        VITE_APP_URL: "https://fleet.laminaraviationapps.com"

    image: laminar-aviation-app:latest
    container_name: laminar-aviation-frontend

    env_file:
      - .env.prod

    ports:
      - "3000:80"

    environment:
      NODE_ENV: production

    restart: unless-stopped

    networks:
      - laminar-network

networks:
  laminar-network:
    driver: bridge
